/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Wrangler.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Wrangler(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/Wrangler.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.146}>
        <mesh geometry={nodes.BODY.geometry} material={materials.BaseMtl} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
        <mesh geometry={nodes.BODY001.geometry} material={materials['Slaughter.001']} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
        <mesh geometry={nodes.BODY002.geometry} material={materials.BatLady} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
        <mesh geometry={nodes.BODY003.geometry} material={materials.BrakeLine} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
        <mesh geometry={nodes.BODY004.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
        <mesh geometry={nodes.BODY005.geometry} material={materials.Embers} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
        <mesh geometry={nodes.BODY006.geometry} material={materials['SpiderID.001']} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
        <mesh geometry={nodes.BODY007.geometry} material={materials.Fluid} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
        <mesh geometry={nodes.BODY008.geometry} material={materials.HotRods} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
        <mesh geometry={nodes.BODY009.geometry} material={materials['Mayan.001']} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
        <mesh geometry={nodes.BODY010.geometry} material={materials['SeaBreeze.001']} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
        <mesh geometry={nodes.BODY011.geometry} material={materials.ShapeShifter} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
        <mesh geometry={nodes.BODY012.geometry} material={materials.Silk} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
        <mesh geometry={nodes.BODY013.geometry} material={materials.SnakeSkin} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
        <mesh geometry={nodes.BODY014.geometry} material={materials.Flare} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
        <mesh geometry={nodes.BODY015.geometry} material={materials.Dominator} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
        <mesh geometry={nodes.BODY016.geometry} material={materials.TopGun} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
        <mesh geometry={nodes.BODY017.geometry} material={materials.Explosion} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
        <mesh geometry={nodes.BODY018.geometry} material={materials.WildWest} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
        <mesh geometry={nodes.BODY019.geometry} material={materials.Zombie} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
        <mesh geometry={nodes.Object_2.geometry} material={materials.glass_back__02} />
        <mesh geometry={nodes.Object_30001.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.support_color} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.headligt_back_red} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.headligt_back_02} />
        <mesh geometry={nodes.Object_27_1.geometry} material={materials.glass_front_bl} />
        <mesh geometry={nodes.Object_27_2.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_27_3.geometry} material={materials.DISK} />
        <mesh geometry={nodes.Object_27_4.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_27_5.geometry} material={materials.glass01} />
        <mesh geometry={nodes.Object_27_6.geometry} material={materials.headligt_front_03} />
        <mesh geometry={nodes.Object_27_7.geometry} material={materials.headligt_front_05} />
        <mesh geometry={nodes.Object_27_8.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_27_9.geometry} material={materials.glass_white__01} />
        <mesh geometry={nodes.Object_27_10.geometry} material={materials.gird} />
        <mesh geometry={nodes.Object_27_11.geometry} material={materials.salon} />
        <mesh geometry={nodes.Object_27_12.geometry} material={materials.headligt_front_01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Wrangler.glb')
